version: '3.8'

services:
  anaconda:
    image: continuumio/anaconda3:latest
    container_name: anaconda
    environment:
      - JUPYTER_ENABLE_LAB=yes  # Activa JupyterLab al iniciar el contenedor
    volumes:
      - /mnt/sdc2/docker_volumes/anaconda_science_data_volume:/home/work  # Monta el directorio actual en /home/jovyan/work en el contenedor
    ports:
      - "8888:8888"  # Expone el puerto 8888 para acceder a JupyterLab
    command: >
      /bin/bash -c "conda install numpy pandas tensorflow -y &&
                    jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"